{% set name = "libpsl" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rockdaboot/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e35991b6e17001afa2c0ca3b10c357650602b92596209b7492802f3768a6285f

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - ninja
    - pkg-config
    - meson
  host:
    - icu
  run:
    - icu

test:
  commands:
    - test -f ${PREFIX}/include/libpsl.h                       # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libpsl.pc                # [unix]
    - test -f ${PREFIX}/lib/libpsl.dylib                       # [osx]
    - test -f ${PREFIX}/lib/libpsl.so                          # [linux]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libpsl.pc exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\psl.lib exit 1               # [win]
    - if not exist %LIBRARY_INC%\\libpsl.h exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\psl-5.dll exit 1             # [win]

about:
  home: https://github.com/rockdaboot/libpsl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A C library to handle the Public Suffix List

extra:
  recipe-maintainers:
    - tschoonj
